name: Analysis

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-20.04

    steps:
    - name: Analysis | Checkout
      uses: actions/checkout@v2.3.4

    - name: Analysis | Setup
      uses: github/codeql-action/init@v1
      with:
        languages: csharp

    - name: Analysis | Build
      uses: github/codeql-action/autobuild@v1

    - name: Analysis
      uses: github/codeql-action/analyze@v1
