name: Package

on:
  release:
    types: [created]

env:
  DOTNET_VERSION: 6.0.100-preview.2.21155.3

jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Package | Checkout
        uses: actions/checkout@v2

      - name: Package | Release
        id: release
        uses: tenhaus/get-release-or-tag@v2

      - name: Package | Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Package | Publish
        uses: drusellers/publish-nuget@v3
        with:
          project-file-path: src/Minio.AspNetCore/Minio.AspNetCore.csproj
          version: ${{ steps.release.outputs.tag }}
          tag-format: '*'
          nuget-key: ${{ secrets.NUGET_API_KEY }}
          include-symbols: true

      - name: Package | Publish | HealthChecks
        uses: drusellers/publish-nuget@v3
        with:
          project-file-path: src/Minio.AspNetCore.HealthChecks/Minio.AspNetCore.HealthChecks.csproj
          version: ${{ steps.release.outputs.tag }}
          tag-format: '*'
          nuget-key: ${{ secrets.NUGET_API_KEY }}
          include-symbols: true
