name: Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Package | Checkout
        uses: actions/checkout@v2

      - name: Package | Release
        id: release
        uses: tenhaus/get-release-or-tag@v2

      - name: Package | Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Package | Publish
        uses: brandedoutcast/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Minio.AspNetCore/Minio.AspNetCore.csproj
          VERSION_STATIC: ${{ steps.release.outputs.tag }}
          TAG_FORMAT: '*'
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true

      - name: Package | Publish | HealthChecks
        uses: brandedoutcast/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Minio.AspNetCore.HealthChecks/Minio.AspNetCore.HealthChecks.csproj
          VERSION_STATIC: ${{ steps.release.outputs.tag }}
          TAG_FORMAT: '*'
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true
