name: Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Package | Checkout
        uses: actions/checkout@v3

      - name: Package | Release
        id: release
        uses: tenhaus/get-release-or-tag@v2

      - name: Package | Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Package | Build
        run: dotnet build -c Release /p:Version=$VERSION $PROJECT
        env:
          PROJECT: src/Minio.AspNetCore/Minio.AspNetCore.csproj
          VERSION: ${{ steps.release.outputs.tag }}

      - name: Package | Publish
        run: dotnet pack -c Release /p:Version=$VERSION $PROJECT
        env:
          PROJECT: src/Minio.AspNetCore/Minio.AspNetCore.csproj
          VERSION: ${{ steps.release.outputs.tag }}

      - name: Package | Build | HealthChecks
        run: dotnet build -c Release /p:Version=$VERSION $PROJECT
        env:
          PROJECT: src/Minio.AspNetCore.HealthChecks/Minio.AspNetCore.HealthChecks.csproj
          VERSION: ${{ steps.release.outputs.tag }}

      - name: Package | Publish | HealthChecks
        run: dotnet pack -c Release /p:Version=$VERSION $PROJECT
        env:
          PROJECT: src/Minio.AspNetCore.HealthChecks/Minio.AspNetCore.HealthChecks.csproj
          VERSION: ${{ steps.release.outputs.tag }}

      - name: Package | Push
        run: dotnet nuget push artifacts/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
