name: Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Package | Checkout
        uses: actions/checkout@v2

      - name: Package | Release
        id: release
        uses: tenhaus/get-release-or-tag@v2

      - name: Package | Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Package | Publish
        run: dotnet pack -c Release -o ./pack /p:Version=$VERSION $PROJECT
        env:
          PROJECT: src/Minio.AspNetCore/Minio.AspNetCore.csproj
          VERSION: ${{ steps.release.outputs.tag }}

      - name: Package | Publish | HealthChecks
        run: dotnet pack -c Release -o ./pack /p:Version=$VERSION $PROJECT
        env:
          PROJECT: src/Minio.AspNetCore.HealthChecks/Minio.AspNetCore.HealthChecks.csproj
          VERSION: ${{ steps.release.outputs.tag }}

      - name: Package | Push
        run: dotnet nuget push pack/*.nupkg
