name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release
        required: true
        default: patch

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04

    steps:
    - name: Release | Checkout
      uses: actions/checkout@v2.3.4

    - name: Release | Previous | Cancel
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ secrets.UPDATE_WORKFLOWS_TOKEN }}

    - name: Release | Tag
      id: tag
      uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ github.event.inputs.release }}
        github_token: ${{ secrets.UPDATE_WORKFLOWS_TOKEN }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Release
      uses: actions/create-release@v1.1.4
      with:
        tag_name: ${{ steps.tag.outputs.version }}
        release_name: ${{ steps.tag.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.UPDATE_WORKFLOWS_TOKEN }}
