name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release
        required: true
        default: patch

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Release | Checkout
        uses: actions/checkout@v2

      - name: Release | Tag
        id: tag
        uses: zwaldowski/semver-release-action@v2
        with:
          bump: ${{ github.event.inputs.release }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.version }}
          token: ${{ secrets.CREATE_RELEASE_TOKEN }}
